#!/usr/bin/env bash
# check-version-bump.sh — post-commit hook (non-blocking).
#
# Detects semver bumps on architecture/CONTRACT-*.md files (via rename)
# and appends notification entries to the federation outbox at
# architecture/.state/pending-notifications.md.
#
# The owner runs `scripts/flush-notifications.sh` at their convenience
# to deliver pending entries via the ask_<consumer>_featurerequest gate.
# This split keeps version bumps fast (just append) and notification
# dispatch deliberate (owner-controlled).
#
# Wire as a post-commit hook (NOT pre-commit — must not block):
#   ln -sf ../../scripts/check-version-bump.sh .git/hooks/post-commit
#
# Source: CHARTER §1.6, feedback/2026-04-28-cross-repo-contract-federation.md

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
cd "$REPO_ROOT"

OUTBOX="${REBAR_OUTBOX:-architecture/.state/pending-notifications.md}"

# Detect renames in architecture/CONTRACT-*.md from the most recent commit.
# A rename like CONTRACT-C1-AGENTS.2.0.md → CONTRACT-C1-AGENTS.3.0.md is
# the rebar-convention signal of a semver bump.
renames=$(git diff-tree --no-commit-id --name-status -r --diff-filter=R \
  --find-renames=80% HEAD 2>/dev/null \
  | awk '$1 ~ /^R/ && $2 ~ /^architecture\/CONTRACT-.*\.md$/ && $3 ~ /^architecture\/CONTRACT-.*\.md$/ {print $2 "|" $3}')

[ -z "$renames" ] && exit 0

# Parse "CONTRACT-<id>.<MAJOR>.<MINOR>[.<PATCH>].md" → "<id>|<version>".
# Bash 3.2 compatible (no extended-glob). Awk does the heavy lifting.
parse_contract_path() {
  local path="$1"
  local base
  base=$(basename "$path" .md)
  base="${base#CONTRACT-}"
  echo "$base" | awk -F. '{
    n = NF;
    if (n >= 2 && $n ~ /^[0-9]+$/ && $(n-1) ~ /^[0-9]+$/) {
      if (n >= 3 && $(n-2) ~ /^[0-9]+$/) {
        ver = $(n-2) "." $(n-1) "." $n;
        for (i = 1; i < n-2; i++) id = (id ? id "." : "") $i;
      } else {
        ver = $(n-1) "." $n;
        for (i = 1; i < n-1; i++) id = (id ? id "." : "") $i;
      }
      print id "|" ver;
    }
  }'
}

mkdir -p "$(dirname "$OUTBOX")"
if [ ! -f "$OUTBOX" ]; then
  cat > "$OUTBOX" <<'EOF'
# Pending Consumer Notifications

<!-- format: rebar-pending-notifications-v1 -->

Auto-generated by `scripts/check-version-bump.sh` (post-commit hook).
Owner runs `scripts/flush-notifications.sh` to deliver pending entries
via the `ask_<consumer>_featurerequest` gate.

Each entry: contract id, old → new version, detected timestamp,
commit, status (pending | sent | dropped). `flush-notifications.sh`
auto-classifies severity (breaking | additive | patch) from the
semver delta unless --severity overrides.

EOF
fi

now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
short_sha=$(git rev-parse --short HEAD)
appended=0

# IFS pipe-separated, parsed on the way in.
echo "$renames" | while IFS='|' read -r old new; do
  old_iv=$(parse_contract_path "$old")
  new_iv=$(parse_contract_path "$new")
  old_id="${old_iv%%|*}"
  old_ver="${old_iv#*|}"
  new_id="${new_iv%%|*}"
  new_ver="${new_iv#*|}"
  # Skip if id changed (rename to a different contract, not a version bump)
  [ "$old_id" = "$new_id" ] || continue
  [ -z "$new_id" ] && continue

  cat >> "$OUTBOX" <<ENTRY

## $new_id: $old_ver → $new_ver
- **detected:** $now
- **status:** pending
- **commit:** $short_sha
- **old_path:** $old
- **new_path:** $new
- **severity:** (auto)
ENTRY
  appended=$((appended+1))
done

# Surface for visibility (stderr so it doesn't interfere with hook output).
pending=$(grep -cE '^- \*\*status:\*\* pending' "$OUTBOX" 2>/dev/null | tr -d ' \n' || echo 0)
if [ "$pending" != "0" ] && [ "$pending" != "" ]; then
  echo "rebar: contract version bump recorded → outbox has $pending pending notification(s); flush with scripts/flush-notifications.sh" >&2
fi
