#!/usr/bin/env bash
# compute-registry.sh — Generate CONTRACT-REGISTRY.md from contract files on disk
# rebar-scripts: 2026.03.20
#
# Usage:
#   ./scripts/compute-registry.sh           Generate architecture/CONTRACT-REGISTRY.md
#   ./scripts/compute-registry.sh --check   Exit 0 if current, 1 if stale
#   ./scripts/compute-registry.sh --stdout   Print to stdout instead of writing file
#
# The contract filesystem IS the registry. This script just renders it.
#
# Exit code: 0 = success/current, 1 = stale (--check mode)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ARCH_DIR="$PROJECT_ROOT/architecture"
REGISTRY="$ARCH_DIR/CONTRACT-REGISTRY.md"
MODE="${1:-generate}"

# ─── Helpers ────────────────────────────────────────────────────────────────

# Parse contract filename → ID + version (reused logic from steward.sh)
parse_contract_file() {
  local filename
  filename="$(basename "$1")"

  local stem="${filename#CONTRACT-}"
  stem="${stem%.md}"

  if [[ "$stem" =~ ^(.+)\.([0-9]+)\.([0-9]+)$ ]]; then
    CONTRACT_ID="${BASH_REMATCH[1]}"
    CONTRACT_VERSION="${BASH_REMATCH[2]}.${BASH_REMATCH[3]}"
  elif [[ "$stem" =~ ^(.+)\.([0-9]+)$ ]]; then
    CONTRACT_ID="${BASH_REMATCH[1]}"
    CONTRACT_VERSION="${BASH_REMATCH[2]}.0"
  else
    CONTRACT_ID="$stem"
    CONTRACT_VERSION="1.0"
  fi
}

# Extract status from contract file (looks for **Status:** or Status: line)
extract_status() {
  local file="$1"
  local status
  status=$(grep -i '^\*\*Status:\*\*\|^Status:' "$file" 2>/dev/null | head -1 | sed 's/.*:\s*//' | tr -d '*' | xargs)
  echo "${status:-draft}"
}

# Extract purpose (first non-empty line after ## Purpose)
extract_purpose() {
  local file="$1"
  awk '/^## Purpose/{found=1; next} found && /^[^#]/ && NF{print; exit}' "$file" 2>/dev/null | head -c 80
}

# Classify by prefix
classify_prefix() {
  local id="$1"
  case "$id" in
    S*) echo "Services" ;;
    C*) echo "Components" ;;
    I*) echo "Interfaces" ;;
    P*) echo "Protocols" ;;
    *)  echo "Other" ;;
  esac
}

# Count implementing files for a contract.
# `grep` returns 1 when there are no matches; under `set -o pipefail` that
# would abort the whole script for any orphan contract. The greps in this
# pipeline legitimately return 1 on empty input, so we run with pipefail
# temporarily disabled.
#
# Two passes, deduplicated by file path:
#   1. Source files matching the standard extension whitelist
#   2. Files anywhere under `bin/` (CLI entry points often have no extension —
#      `bin/ask`, `bin/ask-mcp-server`, `bin/rebar`)
count_implementations() {
  local id="$1"
  set +o pipefail
  {
    grep -rln "CONTRACT:${id}" "$PROJECT_ROOT" \
      --include='*.go' --include='*.ts' --include='*.tsx' --include='*.js' \
      --include='*.py' --include='*.rs' --include='*.java' --include='*.rb' \
      --include='*.jsx' --include='*.sh' 2>/dev/null
    if [ -d "$PROJECT_ROOT/bin" ]; then
      grep -rln "CONTRACT:${id}" "$PROJECT_ROOT/bin" 2>/dev/null
    fi
  } \
    | grep -v "node_modules\|vendor\|dist\|\.git\|architecture/" \
    | sort -u \
    | wc -l | tr -d ' '
  set -o pipefail
}

# ─── Collect Contracts ──────────────────────────────────────────────────────

declare -a services=() components=() interfaces=() protocols=() other=()

for contract in "$ARCH_DIR"/CONTRACT-*.md; do
  [ ! -f "$contract" ] && continue

  basename=$(basename "$contract")

  # Skip non-contract files
  case "$basename" in
    CONTRACT-TEMPLATE.md|CONTRACT-SEAM-TEMPLATE.md|CONTRACT-REGISTRY.md|CONTRACT-REGISTRY.template.md|CONTRACT-GAPS.md)
      continue ;;
    *.impl.md)
      continue ;;
  esac

  parse_contract_file "$contract"
  local_status=$(extract_status "$contract")
  local_purpose=$(extract_purpose "$contract")
  impl_count=$(count_implementations "$CONTRACT_ID")

  entry="| $CONTRACT_ID | $CONTRACT_VERSION | $local_status | $impl_count | ${local_purpose:-—} |"

  category=$(classify_prefix "$CONTRACT_ID")
  case "$category" in
    Services)   services+=("$entry") ;;
    Components) components+=("$entry") ;;
    Interfaces) interfaces+=("$entry") ;;
    Protocols)  protocols+=("$entry") ;;
    *)          other+=("$entry") ;;
  esac
done

# ─── Generate Output ────────────────────────────────────────────────────────

GENERATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

generate_registry() {
  cat <<HEADER
# Contract Registry

<!-- AUTO-GENERATED by scripts/compute-registry.sh — do not edit manually -->
<!-- Generated: $GENERATED_AT -->
<!-- Regenerate: ./scripts/compute-registry.sh -->

HEADER

  # bash 3.2-compatible: pass array entries through a function instead of
  # using `local -n` namerefs (bash 4.3+). macOS ships bash 3.2 by default.
  emit_category() {
    local category="$1"; shift
    [ $# -eq 0 ] && return
    echo "## $category"
    echo ""
    echo "| ID | Version | Status | Impl Files | Purpose |"
    echo "|----|---------|--------|------------|---------|"
    local entry
    for entry in "$@"; do
      echo "$entry"
    done
    echo ""
  }

  emit_category "Services"   ${services[@]+"${services[@]}"}
  emit_category "Components" ${components[@]+"${components[@]}"}
  emit_category "Interfaces" ${interfaces[@]+"${interfaces[@]}"}
  emit_category "Protocols"  ${protocols[@]+"${protocols[@]}"}
  emit_category "Other"      ${other[@]+"${other[@]}"}

  # Contract files section (for tooling compatibility)
  echo "## Contract Files"
  echo ""
  echo "<!-- Plain list of filenames for grep-based tooling -->"
  for contract in "$ARCH_DIR"/CONTRACT-*.md; do
    [ ! -f "$contract" ] && continue
    basename=$(basename "$contract")
    case "$basename" in
      CONTRACT-TEMPLATE.md|CONTRACT-SEAM-TEMPLATE.md|CONTRACT-REGISTRY.md|CONTRACT-REGISTRY.template.md|CONTRACT-GAPS.md)
        continue ;;
      *.impl.md)
        continue ;;
    esac
    echo "- $basename"
  done
  echo ""

  # ─── Contract Health: zombie + shadow detection ──────────────────────────
  # zombie  — contract file exists but no CONTRACT:<ID> headers in source
  #           (deletion candidate unless tracked in TODO.md)
  # shadow  — CONTRACT:<ID> reference in source but no architecture/<ID>.md
  #           file (typo, deleted contract, or not-yet-written spec)

  local zombies=()
  local known_ids=" "  # space-padded list for easy substring matching
  for contract in "$ARCH_DIR"/CONTRACT-*.md; do
    [ ! -f "$contract" ] && continue
    basename=$(basename "$contract")
    case "$basename" in
      CONTRACT-TEMPLATE.md|CONTRACT-SEAM-TEMPLATE.md|CONTRACT-REGISTRY.md|CONTRACT-REGISTRY.template.md|CONTRACT-GAPS.md)
        continue ;;
      *.impl.md)
        continue ;;
    esac

    parse_contract_file "$contract"
    known_ids="$known_ids$CONTRACT_ID "

    local count
    count=$(count_implementations "$CONTRACT_ID")
    if [ "$count" -eq 0 ]; then
      if [ -f "$PROJECT_ROOT/TODO.md" ] && grep -q "$CONTRACT_ID" "$PROJECT_ROOT/TODO.md" 2>/dev/null; then
        zombies+=("- **$CONTRACT_ID** — tracked in TODO.md")
      else
        zombies+=("- **$CONTRACT_ID** — ⚠ untracked, 0 implementing files")
      fi
    fi
  done

  # Shadow detection: every CONTRACT:<ID>.<v.v> reference in source,
  # filtered to IDs not in known_ids. Same extension whitelist + bin/
  # second-pass as count_implementations() so we don't miss CLI scripts.
  local shadows_tmp
  shadows_tmp="$(mktemp)"
  set +o pipefail
  {
    grep -rEhno 'CONTRACT:[A-Za-z0-9_-]+\.[0-9]+\.[0-9]+' "$PROJECT_ROOT" \
      --include='*.go' --include='*.ts' --include='*.tsx' --include='*.js' \
      --include='*.py' --include='*.rs' --include='*.java' --include='*.rb' \
      --include='*.jsx' --include='*.sh' 2>/dev/null
    if [ -d "$PROJECT_ROOT/bin" ]; then
      grep -rEhno 'CONTRACT:[A-Za-z0-9_-]+\.[0-9]+\.[0-9]+' "$PROJECT_ROOT/bin" 2>/dev/null
    fi
  } \
    | grep -v "node_modules\|vendor\|dist\|\.git\|architecture/" \
    | sed -E 's/^[^:]*:[^:]*://; s/^CONTRACT://; s/\.[0-9]+\.[0-9]+$//' \
    | sort -u > "$shadows_tmp"
  set -o pipefail

  local shadows=()
  while IFS= read -r ref_id; do
    [ -z "$ref_id" ] && continue
    case "$known_ids" in
      *" $ref_id "*) ;;  # known — not a shadow
      *) shadows+=("- **$ref_id** — referenced in source, no architecture/CONTRACT-${ref_id}.*.md found") ;;
    esac
  done < "$shadows_tmp"
  rm -f "$shadows_tmp"

  if [ ${#zombies[@]} -gt 0 ] || [ ${#shadows[@]} -gt 0 ]; then
    echo "## Contract Health"
    echo ""

    if [ ${#zombies[@]} -gt 0 ]; then
      echo "### Zombies — contract files with no implementing code"
      echo ""
      echo "(Deletion candidates unless intentionally pre-impl. Add a TODO.md entry"
      echo "to suppress this warning while implementation is in flight.)"
      echo ""
      for z in "${zombies[@]}"; do
        echo "$z"
      done
      echo ""
    fi

    if [ ${#shadows[@]} -gt 0 ]; then
      echo "### Shadow refs — code references to nonexistent contracts"
      echo ""
      echo "(Either write the missing contract file or fix the typo in source.)"
      echo ""
      for s in "${shadows[@]}"; do
        echo "$s"
      done
      echo ""
    fi
  fi
}

# ─── Execute Mode ───────────────────────────────────────────────────────────

case "$MODE" in
  --check)
    if [ ! -f "$REGISTRY" ]; then
      echo "FAIL: $REGISTRY does not exist. Run scripts/compute-registry.sh to generate."
      exit 1
    fi

    # Generate to temp and compare
    tmpfile=$(mktemp)
    generate_registry > "$tmpfile"

    # Compare ignoring the timestamp line
    if diff <(grep -v "^<!-- Generated:" "$REGISTRY") <(grep -v "^<!-- Generated:" "$tmpfile") >/dev/null 2>&1; then
      echo "OK: Registry is current."
      rm "$tmpfile"
      exit 0
    else
      echo "STALE: Registry needs regeneration. Run scripts/compute-registry.sh"
      rm "$tmpfile"
      exit 1
    fi
    ;;

  --stdout)
    generate_registry
    ;;

  *)
    generate_registry > "$REGISTRY"
    echo "Generated: $REGISTRY"
    ;;
esac
